apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: rag-chatbot
  labels:
    app.kubernetes.io/name: rag-chatbot
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "secretpassword"
  MONGO_URI: "mongodb://admin:secretpassword@mongodb-0.mongodb.rag-chatbot.svc.cluster.local:27017/rag_chatbot?authSource=admin"
  JWT_SECRET: "change-me-to-a-real-secret-of-at-least-32-characters!!"
  SESSION_SECRET: "change-me-to-another-secret-of-at-least-32-characters!!"
  GOOGLE_API_KEY: "your-google-api-key"
  GOOGLE_SEARCH_KEY: "your-google-search-key"
  GOOGLE_CSE_ID: "your-google-cse-id"
