apiVersion: v1
kind: Service
metadata:
  name: chatbot
  namespace: rag-chatbot
  labels:
    app: chatbot
spec:
  type: ClusterIP
  selector:
    app: chatbot
  ports:
    - port: 8000
      targetPort: 8000
